# Generated by Django 4.0.1 on 2022-01-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de empresa')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('web', models.CharField(max_length=255, verbose_name='Página web')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('residencia', models.CharField(max_length=255, verbose_name='Residencia')),
                ('estado', models.BooleanField(default=True)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('nombreBD', models.CharField(default=None, max_length=50)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
    ]
