# Generated by Django 4.0.1 on 2022-01-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombreBD',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
