# Generated by Django 4.0.1 on 2022-01-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rubro',
            field=models.CharField(max_length=255, null=True, verbose_name='Rubro de la empresa'),
        ),
    ]
