# Generated by Django 4.0.1 on 2022-02-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0002_cliente_rubro'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la sección json')),
                ('conversacion', models.CharField(max_length=500, verbose_name='Preguntas y respuestas')),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_admin.cliente')),
            ],
            options={
                'db_table': 'data_set',
                'ordering': ['id'],
            },
        ),
    ]
