# Generated by Django 4.0.1 on 2022-02-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0003_data_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='conversacion',
            field=models.TextField(verbose_name='Preguntas y respuestas'),
        ),
    ]
