# Generated by Django 4.0.1 on 2022-02-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0004_alter_data_set_conversacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalizar_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_admin.cliente')),
            ],
            options={
                'db_table': 'personalizar_chat',
                'ordering': ['id'],
            },
        ),
    ]
