# Generated by Django 4.0.1 on 2022-02-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0005_personalizar_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personalizar_chat',
            new_name='apariencia',
        ),
    ]
