# Generated by Django 4.0.1 on 2022-02-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0006_rename_personalizar_chat_apariencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apariencia',
        ),
    ]
