# Generated by Django 4.0.1 on 2022-01-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_alter_userprofile_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
