# Generated by Django 4.0.1 on 2022-01-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_alter_userprofile_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id'], 'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
