# Generated by Django 4.0.1 on 2022-01-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0004_alter_userprofile_options_alter_userprofile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_cliente',
        ),
    ]
