# Generated by Django 4.0.1 on 2022-01-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0001_initial'),
        ('profile_user', '0005_remove_userprofile_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_admin.cliente'),
        ),
    ]
