# Generated by Django 4.0.1 on 2022-02-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0006_userprofile_id_cliente'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='usuarios',
        ),
    ]
