# Generated by Django 4.0.1 on 2022-02-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0003_data_set'),
        ('chatbot', '0003_alter_chat_user_options_alter_chat_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_user',
            name='cliente_empresa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_admin.cliente'),
        ),
    ]
