# Generated by Django 4.0.1 on 2022-01-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chat_user_id_session_chat_user_key_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_user',
            name='nombre_alias',
            field=models.CharField(default=None, max_length=50, verbose_name='nombre_alias'),
        ),
    ]
