# Generated by Django 4.0.1 on 2022-02-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chat_user_cliente_empresa_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat_user',
            table='historial_chat',
        ),
    ]
