# Generated by Django 4.0.1 on 2022-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chat_user_nombre_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_user',
            name='nombre_alias',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='nombre_alias'),
        ),
    ]
