# Generated by Django 4.0.1 on 2022-02-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_chat_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_user',
            name='registrado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
