# Generated by Django 4.0.1 on 2022-01-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_chat_user_nombre_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_user',
            name='respuesta',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Respuesta'),
        ),
    ]
