# Generated by Django 4.0.1 on 2022-02-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chat_user_registrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_user',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='chat_user',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='chat_user',
            name='historial',
            field=models.TextField(null=True, verbose_name='Historial de preguntas y respuestas'),
        ),
    ]
