# Generated by Django 4.0.1 on 2022-01-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chat_user_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_user',
            name='nombre_alias',
        ),
    ]
