# Generated by Django 4.0.1 on 2022-02-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_remove_chat_user_pregunta_remove_chat_user_respuesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_user',
            name='historial',
        ),
        migrations.AddField(
            model_name='chat_user',
            name='pregunta',
            field=models.CharField(max_length=100, null=True, verbose_name='Escribir mensaje'),
        ),
        migrations.AddField(
            model_name='chat_user',
            name='respuesta',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Respuesta'),
        ),
    ]
