# Generated by Django 4.0.1 on 2022-02-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0004_alter_data_set_conversacion'),
        ('chatbot', '0008_remove_chat_user_historial_chat_user_pregunta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatbot_style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_header', models.CharField(max_length=100)),
                ('titulo_cuerpo', models.CharField(max_length=100)),
                ('botones', models.CharField(max_length=100)),
                ('text_bienvenida', models.CharField(max_length=255)),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_admin.cliente')),
            ],
            options={
                'db_table': 'chatbot_style',
                'ordering': ['id'],
            },
        ),
    ]
