# Generated by Django 4.0.1 on 2022-02-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_chatbot_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_user',
            name='key_session',
        ),
        migrations.AddField(
            model_name='chat_user',
            name='key_session_alias',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Alias usuario'),
        ),
    ]
