# Generated by Django 4.0.1 on 2022-02-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_remove_chat_user_key_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_user',
            name='respuesta',
            field=models.TextField(default=None, null=True, verbose_name='Respuesta'),
        ),
    ]
