# Generated by Django 4.0.1 on 2022-02-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_alter_chat_user_respuesta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatbot_style',
            table='chatbot_estilo',
        ),
    ]
