# Generated by Django 4.0.1 on 2022-02-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_alter_chatbot_style_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot_style',
            old_name='id_empresa',
            new_name='id_empresa_cliente',
        ),
        migrations.AlterField(
            model_name='chatbot_style',
            name='botones',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chatbot_style',
            name='text_bienvenida',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='chatbot_style',
            name='titulo_cuerpo',
            field=models.CharField(max_length=255),
        ),
    ]
